### ISSUE TITLE
Pretrained ResNet 

### ISSUE THREAD

**Issue by ElifCerenGok** [sun-hailong/LAMDA-PILOT#11]
Hello,
I really enjoy working with this great framework, thank you so much.
I'm interested in utilizing the ResNet architecture as well. Would you be able to provide the pre-trained ResNet implementation?
Thank you in advance.

**Comment by sun-hailong** [comment]
Hi @ElifCerenGok,
If you're considering using the pre-trained ResNet, I suggest checking out the PyCIL toolbox (https://github.com/G-U-N/PyCIL). It could streamline your process effectively.
