### ISSUE TITLE
Error when using multiple GPUs

### ISSUE THREAD

**Issue by PixelChen24** [sun-hailong/LAMDA-PILOT#12]
When I'm running the `l2p.json` experiment and use 4 GPUs (i.e. cuda:5, cuda:6, cuda:7, cuda:8 on my machine), the program throws this exception:
```python
AttributeError: 'DataParallel' object has no attribute 'backbone'
```
![image](https://github.com/sun-hailong/LAMDA-PILOT/assets/36230079/146c61b6-cfa3-4889-af40-5ae61dacb44d)
How to fix it? I have never experienced multiple GPUs running. Look forward to your response.

**Comment by sun-hailong** [comment]
Hi @PixelChen24,

I'm sorry to learn about the issue. It seems that our initial code didn't fully account for the scenario you've encountered. I recommend trying to run the process using a single GPU instead of multiple GPUs. This adjustment might resolve the problem you're facing.

**Comment by PixelChen24** [comment]
It's very strange. When I conduct the `icarl.json` exp, it works well with multiple GPUs. But it just doesn't work when conducting the `l2p.json` exp

**Comment by sun-hailong** [comment]
Yes, the discrepancy in the code has indeed led to this issue. However, it's important to note that within this framework, using icarl or l2p will not actually result in acceleration. Therefore, I suggest opting for a single GPU setup.

**Comment by PixelChen24** [comment]
I see. Thank you very much
