### ISSUE TITLE
Seems that Dual-Prompt's implement has some issues

### ISSUE THREAD

**Issue by ganchi-huanggua** [sun-hailong/LAMDA-PILOT#14]
In backbone/vision_transformer_dual_prompt.py, line 250, it seems that args "g_prompt" isn't concatenated with x, and doesn't participate in forward propagation. Maybe I made a mistake, but as stated in the original paper, g_prompt needs to be update, and e_prompt has the similar problem. I'm looking forward to your response. Thank you very much.
![image](https://github.com/sun-hailong/LAMDA-PILOT/assets/61151075/0efef0da-6bdf-4d5a-88e8-62296a2e031f)
![image](https://github.com/sun-hailong/LAMDA-PILOT/assets/61151075/c3a714f6-34d5-41f4-aef9-923fa30e3b8b)

**Comment by sun-hailong** [comment]
Hi @ganchi-huanggua ,
Thank you for your interest in our repository! Regarding the issue you've raised, I believe you will find the solution between lines 486 and 493 in backbone/vision_transformer_dual_prompt.py. Additionally, you can refer to our "dualprompt.json" file for the configuration parameters. Please note that the key "PreT_Attention" specifies the attention mechanism employed for dualprompt in prefix tuning.

**Comment by ganchi-huanggua** [comment]
Sorry, I'm careless and made the mistake. Thanks for your patient answer. Have a nice day! :)
