### ISSUE TITLE
imageneta-B0-Inc20

### ISSUE THREAD

**Issue by Geeks-Z** [sun-hailong/LAMDA-PILOT#16]
![image](https://github.com/sun-hailong/LAMDA-PILOT/assets/71618219/1ae50c14-25d8-4751-b9ec-fc6735cbd6f6)

![image](https://github.com/sun-hailong/LAMDA-PILOT/assets/71618219/88ab7d2b-09b0-4210-98f3-f2359da5a462)

**Comment by zhoudw-zdw** [comment]
It seems ImageNet-A does not have so many instances for replay.
