### ISSUE TITLE
Why L2 norm was not always adopted in the exemplar construction?

### ISSUE THREAD

**Issue by lijiaqi** [sun-hailong/LAMDA-PILOT#19]
Hi,

Firstly, thanks for sharing the code with the community!

When I read the code, I found that when constructing the exemplar set, $L_2$-norm was sometimes adopted but sometimes not.

Could you please provide any help?

Calculating the sample features vectors,
https://github.com/sun-hailong/LAMDA-PILOT/blob/b2539374a49e4cafd1a6f4dfc79ca82e8c26f444/models/base.py#L230

https://github.com/sun-hailong/LAMDA-PILOT/blob/b2539374a49e4cafd1a6f4dfc79ca82e8c26f444/models/base.py#L249

https://github.com/sun-hailong/LAMDA-PILOT/blob/b2539374a49e4cafd1a6f4dfc79ca82e8c26f444/models/base.py#L301

https://github.com/sun-hailong/LAMDA-PILOT/blob/b2539374a49e4cafd1a6f4dfc79ca82e8c26f444/models/base.py#L328

https://github.com/sun-hailong/LAMDA-PILOT/blob/b2539374a49e4cafd1a6f4dfc79ca82e8c26f444/models/base.py#L347

Calculating the sample mean,
https://github.com/sun-hailong/LAMDA-PILOT/blob/b2539374a49e4cafd1a6f4dfc79ca82e8c26f444/models/base.py#L232

https://github.com/sun-hailong/LAMDA-PILOT/blob/b2539374a49e4cafd1a6f4dfc79ca82e8c26f444/models/base.py#L303

https://github.com/sun-hailong/LAMDA-PILOT/blob/b2539374a49e4cafd1a6f4dfc79ca82e8c26f444/models/base.py#L330

https://github.com/sun-hailong/LAMDA-PILOT/blob/b2539374a49e4cafd1a6f4dfc79ca82e8c26f444/models/base.py#L400

However, the $L_2$-norm was not applied here:

https://github.com/sun-hailong/LAMDA-PILOT/blob/b2539374a49e4cafd1a6f4dfc79ca82e8c26f444/models/base.py#L348

**Comment by sun-hailong** [comment]
Hi @lijiaqi ,
Thanks for your attention. We will check this problem and fix it in a future version.
