### ISSUE TITLE
Code Support of "Learning without Forgetting for Vision-Language Models" (PROOF)

### ISSUE THREAD

**Issue by jeff024** [sun-hailong/LAMDA-PILOT#2]
Thanks authors for releasing this fantastic toolbox! This great work saves my life! I'm just wondering whether there will be support for a recent work also from you on "Learning without Forgetting for Vision-Language Models" (PROOF)? It would be great if you could also release support for this wonderful work also.

Many thanks in advance!

**Comment by zhoudw-zdw** [comment]
Hi, @jeff024, thanks for your interest in our work.

Currently, the work you mentioned is under submission, and we will indeed include it in the current repo soon. However, it depends on the submission process, and we cannot make any promises.

I will let you know when we are ready.
