### ISSUE TITLE
Questions regarding dualprompt

### ISSUE THREAD

**Issue by MagnusOstertag** [sun-hailong/LAMDA-PILOT#20]
Hi @sun-hailong ,
thanks for the great work!

I was going through the code for `dualprompt` and now have a few small questions / observations:

*  the `easydict` library is not part of the requirements, but is imported
* `vision_transformer_adapter` in `inc_net` is undefined (probably it should be `vit_adapter`)
* why do we need `get_original_backbone()` for dualprompt ViT?
* regarding the parameters in `dualprompt_inr.json` or `dualprompt.json`, a few parameters seem strangely or unnecessarily set
  * `reinit_optimizer` doesn't change anything in the code, the optimizer is reinitialized regardless?!
  * `prefix` is only logged, but not used
  * `global_pool`, `initializer`, `predefined_key` is set, but nowhere used
  * in `timm.create_model()` both for dualprompt and l2p both the `prompt_init` and `prompt_key_init` arguments are set to the same argument (and consequently the `prompt_init` parameter is not used) - which is also upstream in the dualprompt implementation

Best,
Magnus

**Comment by sun-hailong** [comment]
Hi @MagnusOstertag ,
Sorry for the confusion. Some hyperparameters are taken from https://github.com/JH-LEE-KR/l2p-pytorch. For convenience, we have not yet removed some unused parameters.
