### ISSUE TITLE
Bugs in Der and Foster?

### ISSUE THREAD

**Issue by Deexaa** [sun-hailong/LAMDA-PILOT#25]
Thanks for your sharing!
I'd be grateful if you could help me with the bug when reproducing the der.json & foster.json on VTab.

Details belike:
File "LAMDA-PILOT-main/models/base.py", line 260, in _construct_exemplar
i = np.argmin(np.sqrt(np.sum((class_mean - mu_p) ** 2, axis=1)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "envs/pilot/lib/python3.11/site-packages/numpy/core/fromnumeric.py", line 1325, in argmin
return _wrapfunc(a, 'argmin', axis=axis, out=out, **kwds)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "pilot/lib/python3.11/site-packages/numpy/core/fromnumeric.py", line 59, in _wrapfunc
return bound(*args, **kwds)
^^^^^^^^^^^^^^^^^^^^
ValueError: attempt to get argmin of an empty sequence

**Comment by CLLab-NJU** [comment]
This will happen when the exemplars exceed total training instances. Try setting a smaller value for exemplars or setting fixed_memory to false.
