### ISSUE TITLE
How to solve the situation of one class increment ?

### ISSUE THREAD

**Issue by boshuaiYu** [sun-hailong/LAMDA-PILOT#30]
I want to know how to solve the situation of one class increment. When I used the code and set the increment as 1, the loss is 0. That seems that the ce-loss is out of effect, so the model is not trained. So i want to know how to solve the problem, like modifying the loss as bceloss?

**Comment by zhoudw-zdw** [comment]
It seems modifying the loss calculation can somehow solve this problem. Anyway, I think the problem is more related to how to train a DNN for a single class rather than continual learning.
