### ISSUE TITLE
About the combination of ADAM and CODA-Prompt

### ISSUE THREAD

**Issue by brillant222** [sun-hailong/LAMDA-PILOT#31]
Hello, I appreciate your work very much, but now I have encountered some problems in the learning process. Aper can be fine-tuned using the VPT method, so can Aper be combined with CODA-Prompt to use CODA-Prompt to fine-tune the pre-trained model in the first stage?

Looking forward to your reply

**Comment by zhoudw-zdw** [comment]
Hi, CODA-Prompt is not a tuning technique, and its core idea is also VPT. Please check the paper for more details.
