### ISSUE TITLE
Clarification on orth_loss and classifier_align Functions

### ISSUE THREAD

**Issue by 1171000712** [sun-hailong/LAMDA-PILOT#34]
Hello,
Thank you for sharing the code for your paper "MOS: Model Surgery for Pre-Trained Model-Based Class-Incremental Learning". I found the work very insightful!

While going through the code, I noticed the use of the functions orth_loss and classifier_align, but I couldn't find these mentioned or explained in the paper. Could you kindly provide some clarification on:
The purpose of these functions and how they fit into the methodology described in the paper.
Any additional implementation details or intuition behind these functions.

Thank you in advance for your time and help!

**Comment by sun-hailong** [comment]
Hi @1171000712 , thanks for your interest in our work. This part is referenced from the paper "[SLCA](https://arxiv.org/abs/2303.05118)", which improves the classification layer by modeling the class-wise distributions and aligning the classification layers in a post-hoc fashion. This helps to align the representation layer and the classification layer more effectively.
