### ISSUE TITLE
How to use CIFAR100 dataset with image size 32 instead of 224?

### ISSUE THREAD

**Issue by abhinab303** [sun-hailong/LAMDA-PILOT#35]
I edited the `l2p.json` file and changed the dataset to `"cifar100"` keeping everything else fixed. I get the following error: `AssertionError: Input image height (32) doesn't match model (224).`

**Comment by zhoudw-zdw** [comment]
See https://github.com/sun-hailong/LAMDA-PILOT/blob/main/exps/ease.json and https://github.com/sun-hailong/LAMDA-PILOT/blob/main/exps/aper_aperpter.json

**Comment by zhoudw-zdw** [comment]
Note that VIT-B16 cannot handle 32*32 inputs. For your own requirements, you need to find a pre-trained model that is compatible with 32*32 images.
