### ISSUE TITLE
How to Using the Toolbox with ImageNet1k Pre-training

### ISSUE THREAD

**Issue by yunbolyu** [sun-hailong/LAMDA-PILOT#4]
Thank you for the excellent toolbox on pre-trained model-based continual learning. I've gone through the README.md and inspected the provided files. Could you guide me on how to use the model on pre-trained ImageNet1k? It seems straightforward to run the model retrained on ImageNet21k, yielding impressive results.

**Comment by sun-hailong** [comment]
Hi @yunbolyu,
If you would like to use the toolbox with ImageNet1k pre-training, you can modify the "backbone_type" in the JSON files. For example, you can open the vision_transformer_l2p.py, and at the bottom, you'll find some registered models. This means you can use these models as your backbone.

**Comment by yunbolyu** [comment]
Thanks for your answer. I think the problem is the old version of timm will make problems like this `RuntimeError: Unknown model (vit_base_patch16_224.augreg_in1k)`. After updating to a new version, everything worked. Thanks for your rapid answer : )
